/**
 * The icons in the clue sheet (see studentIcons.ts), a cell each in this
 * order, by what the table shows: "school/Abydos", "role/Tank", "gift/...".
 *
 * GENERATED FILE - do not edit by hand. Run `npm run students`.
 */
export const clueIcons: string[] = [
  "damage/Explosive",
  "damage/Mystic",
  "damage/Piercing",
  "damage/Sonic",
  "defense/Composite",
  "defense/Elastic",
  "defense/Heavy",
  "defense/Light",
  "defense/Special",
  "gift/Airbook Rare",
  "gift/Antique Egg Handicraft",
  'gift/Board Game "The Life"',
  "gift/Finest Maple Bonsai",
  "gift/Lace Pillow",
  "gift/Mille-Feuille Traditional Parfait",
  "gift/Music Concert Ticket",
  "gift/Nutrient-Packed Multivitamin Gummies",
  'gift/Samuela "The Beyond"',
  "gift/Sewing Kit",
  "gift/Sophisticated Hairbrush",
  "gift/Streets of Thugs Vol. 1",
  "gift/Three Times a Day Dumbbell Set",
  "role/Dealer",
  "role/Healer",
  "role/Support",
  "role/Tank",
  "role/T.S.",
  "school/Abydos",
  "school/Arius",
  "school/Etc.",
  "school/Gehenna",
  "school/Highlander",
  "school/Hyakkiyako",
  "school/Millennium",
  "school/Red Winter",
  "school/Sakugawa",
  "school/Shanhaijing",
  "school/SRT",
  "school/Tokiwadai",
  "school/Trinity",
  "school/Valkyrie",
  "school/Wildhunt",
];
