import { reveal } from "../helpers/obscure";

/**
 * The picture game's answers for each kind, in the student table's order of
 * the one who stands for each: its cell in the picture sheet and in the
 * shape sheet, then the places in the student table of the students it
 * belongs to, that one first. Two base-36 characters each, a picture to an
 * entry. Stored scrambled, so which cell is whose can't be read off the code
 * at a glance.
 *
 * GENERATED FILE - do not edit by hand. Run `npm run build:guess`.
 */
export const HALOS =
  "YApYQERZXxd3HElDDGEKWUVABVtZb1oWQhNjWloRQAtBETlbDUNHYgdFRxhaDxB3WRVHBn9ZXkdAWVgSNV1dX0dhWhNEQlgcDHMCV0tEZF0dWERcXBdzUFQEQSFEWBxHDl0ZchpQBFhiAlkfRAhcU3daSUATYBFZFkUdQREoW11DF2YRRUYfWgEQJ1kLX0c3WltEEVpbF3BEVRFHPFgPRg1FXEZyA1UUQCZEWUBFCF1IcFFTEVhjB1tHRABfVG9bVEESYwJaBEAaQRE6WQlDH2FQXk1YWwsRMFgJQBN/Wx1GAlkAEnpdVl9EJ1sERBpdGgxwW1QBRDxbXkEZRV9FcV1VA0ciX1FYRA1cSHMZVApBI0RbEEVaXVJ3CUlDB2MHWQdCBEEQIFsSQwBlW0VERVkMEDZbUF9GOVsYRAJYFRUyRFQWRyZYHkUCRVxScRtVC0ApRFpDRgJdWXAOSUFNYgVZDkcNQRItWAZCRGcGRUUHWh4RcltWX0VhWAtFRlsYDHJbVQdFYFpdWEQIXhFyXFEeWGMYWABFXFhWb1kEQwZiXloXWFgBEjRZUl9FPFsDRUxdFAxyEFZFRWpZBFhFCl9BcglXC1hiUFgaRQtfV29aBkAVYgtaB0IeQRF3WAlCEGZaRUcFWgQRJl1UX0ZkWRhFElteDHEBVh1FNFpfWEZRXlByAFYGQilEWRJGAFxJcgRJQx1gHlgeQF9BEDJYFEIfZ11FRhxbFBE2XVNfRyVaHEUOX1sMchlWREZjW1FBHEVcVHIMV0JYYANYDkZbWU9vWABBEWFdXBFYWV4SIFoEQQd/WQ5FG1sPFXZEVhlEZloKQQFFXFVzAVcXWGFeW01GDFkXb1sQQAxhDl1HWFgDE3NaAkdAf1pcRUVbBRUnRFYbRj1aAEcORV1ScxJXGUBjRFlCRVtfS3dZSUAVYxFbGFhbGhE7WghfRCVZGUYaXx4McR1XQ0Y8XhtYRhhdVXEYUxtYYVlYFkYYWENvWwhCHmEaXBVYWRoSN1ofRhZmEkVEE1peE3NdUl9FYlkPR0VdFQxxEFUUR2FEWw5EH14UdgZJQARjW1oVQh9BEC1bEUAWZw1FRhVZCxMrXQ9fRTdYW0cdXwgMc1FVRUc5RFsCRB5eS3ZcSUBMYxhaGEEAQRB0WAFAGWAcXwFYWV0RIFsLRRB/Wh1ETFoCF3NEVgpEZFsbWEUZX09wHlMfWGBeWRpHHkERdVtcQAx/WVxGE1oUDHEaVkFAa0RaHUQBWRlvWxZDEWcLXxdYWg4SLlwBX0c1Wg1AEkVeV3IdURRYYRhbBUABQRE0WVVHHWVfRUYTWgsUKV5dX0ZgWFBAH19UDHANVBZAI0RZHEYbWVFvWlVCDWceRUdAWFgVc0RXHEQgXVBYRwddTXYOSUEYY1xcE1haXRByXQ5fR2ZaA0EYRVxJcVxQHEIyRFobRlhYU3UcSUEWYA1cDFhZXxF1XlVFRX9YE0YEX18McFFXH0JnRFkNRR5bFW9bHUBBZQ5FRBlZXRYkRFRDRWpeAFhEUV1YdQJJQAZiUF8fWFsAEjteC19EOFsNQhtFXxJyHlMDWGIKWB1CGEESOlgPRQx/Wl1HF15cDHMdV0RDYURYTUYBWhRvWRNAH2RdRUQYWh8XdURUHkZlX14=";

export const WEAPONS =
  "Z1lYG0RZXxd3HElDDGFaWUVYWB4QOVhXQBFnCkVEBFoPEHBZCl9GOFpeREBYHRQxRFccQGZYXEYCXFUMcRpXGERlWRhYRxpfUHNfUAdYYxpZB0RRXFd2GklDTWIDWU1FG1hXb1sOQRFjCVgHQFtBEiBYDEMWYhxFQERbHhAgXRxfRyZZGUQQWAMMcltXQ0Q2W19DR0VfSnMdVRVGKkRdQ0QeXUd3HUlCF2EHWRxHUFtCb1gHQBVjAUVEG11ZEClbFUcHf1ocRkBZBhJ7X1xfQGdZXEQYWgoMcF9XGkQ+WlBBR0VdQXADVR1AJERbB0cMXU9wX1AeWGIGWBBEGV5RdFBJQkRhUVkFRRBYUG9ZUUJFYxpFRUxbARAwRFYZRSdYHUJHRV8QcBFVBlhgC1tFRB9cWHYZSUERYVtZA0UfQRN2WA9DDGcSRUcRWw4QOlsDX0BrWFpEDloJDHMZVENFY1wHWEcIXEFyWVZAWGIQWUBFW19Vb1kNQRxiW1tAWFsPEDtZUUcZf1gFRUJYWBU1RFYbRSRZX0cXRVkZcgtURFhiUVsFRVFZWW9bVkBFYlFYGVhZBRR0WQRBDH9bXUcZWA8SNERWQ0YlWQpHB0VdU3EdVBdBYURZQEUOXEV2WUlBBGNZWBJGWkERNVkMQhNhXkVFRVkZEStbEEUOf1kLRhZYBBEvRFYFRDxZA0BCRV8TcRFUGEBmRFodRwVcVXZeSUIQYgRYDkJfQRIyWAdBRGBQXBxYWwESLVpUX0Y6WVpGRl0CDHMDVBZGZl0MWEZRXFZxCUlAEmNdWxZBXEEQJFsCQRdmHUVFDlkAEidEVB5GIVoMQENFX0FwEFcVQGBEWhpED19Hd1xJQxFiAlscQQ1BEzNYXEEdYBJFRA5ZHxIpXFVfQGZYEEYfXVwMcVxVEkY/RFsQRVFfTW9YUEETYQZfB1haGhNwWgpFBn9ZCEREWx0WK0RXFUc3WhhBF0VfEXBdVwFBMkRYE0YTX1NvWhJHRmEcRUUDWBgSOV0HRg5/WgRGGVpdFXREVBZEPVtYQAxFXUlwBlZBWGMMWBJHXVhOb1pXQhxgXUVHBVoCEyJeE19EYFsZRxZdCAxzWFYBRztdA1hHDl1McAFTFlhgEVkXRwNBEDpYE0AfZlxFRAJYWRMvXQxfRSdcWUcZWhkMcV5WCUc9Xg1YRANdR3AHUkNYZ1paTEcbQRE6Wg9AAn9ZHEZCWhoMcF5UAkcrRFlFRlxeWW9aAkBDZ1BFR01YVBR6RFYcRGRcCFhECl5RdwtTEFhjX1oCQA1BEitZHUcSf1sRRB9dCgxwHFcHQDtEWUJHUFlJdV9JR0JjXl0eQlFBEC1YV0cfZVFFRwZaCxQvRFUGRzpcGVhFX1wXdxlJQh1jAF0CWFlVEiVdVV9FZlkLQU1FXkJxDFAVWGMOWBlBDkERMVkXRh9/WARHRFwBDHEeVRZBPF4IWEYHXkp2G1MHWGEQWQRBEUERKVkWRUR/Wl5ETF9cDHIOUUJCYURbDkcdWxRvWVdCGmVdRUcQXVUWJURWCUBqXg5YRB1eSHUBSUBMYAtfHlhYBhM2Xg5fRz5bGkIYRVkTcF5THlhjH1sMQgdBEnZaBEUbf1tYRQ5fHQxyGFcEQiJEWBhHW1tVb1sJR0dlH0VHRlhfFjtEVAJHZ14QWEUGXld0WUlBTWIRXkZYWFoSe19RX0YqWBhDQUVfVHdeUkVYY1pZEENe";

/**
 * Each weapon's name, in WEAPONS' order. Plain: a name says nothing of whose
 * it is.
 */
export const WEAPON_NAMES: string[] = [
  "Wine Red/Admire",
  "Multi-Tactical",
  "Ideal",
  "My Necessity",
  "Destroyer of Denouement",
  "Eye of Horus",
  "Crack Shot",
  "Auto Lacquer",
  "Twin Dragons",
  "Daily Cutlery",
  "White Fang 465",
  "Whip of Love",
  "Modern Millennium Dumbbell",
  "Blood 'n' Gunpowder",
  "Silent Solution",
  "Type 575 Grenade Launcher",
  "Mark of Gluttony",
  "Impalement",
  "Mini No. 5",
  "Demon's Roar",
  "Trick or Trick",
  "Diner's Outlaw",
  "Sincerity",
  "Sleeping Companion Ⅱ",
  "Logic & Reason",
  "Blow Away",
  "Surprise Party",
  "Professor K",
  "Safety",
  "Indiscriminate Shooter",
  "Fancy Light",
  "Big Eye",
  "The Great I's Pistol",
  "Sweet Dessert",
  "Lunch Club Defense Gun Type A",
  "Happy Smile Gun",
  "Auto Aimer",
  "Meister Zero",
  "Common Sense",
  "Support Pointer",
  "Echo Link",
  "Lunch Club Defense Gun Type B",
  "Tactical Therapy",
  "Library Ruler",
  "Sweet Driver",
  "Manifestation of Justice",
  "Izuna-Style Super Ninja Tool",
  "Sakura Bonbon",
  "Supernova: The Sword of Light",
  "Fresh Inspiration",
  "Unique Idea",
  "Chistka",
  "Sagittarius Night",
  "Nyan's Dash",
  "Et Omnia Vanitas",
  "Honest Wish",
  "Justice Black",
  "Valkyrie Service Pistol No.3",
  "Beyond Lumination",
  "Piety",
  "Concert T-Shirt Cannon",
  "Hot Shot",
  "Vernost",
  "Crimson Calamity",
  "Valkyrie Standard Rifle No. 14",
  "Portable Emergency Kit",
  "Backdoor",
  "Soft Resolution",
  "Volume Suppressor",
  "Reverence",
  "Gray Balalaika",
  "RABBIT Type 31 Submachine Gun",
  "RABBIT Type 26 Machine Gun",
  "RABBIT Type 39 Rifle",
  "Funny Fireworks",
  "Pandemonium Society Standard Gun",
  "Michiru-Style Overflow Shotgun",
  "Tsukuyo-Style Submachine Gun",
  "Saint Predator",
  "Identity",
  "Scorpius",
  "Crimson Calamity",
  "Mini No. 5",
  "Arius Assault Rifle",
  "RABBIT Type 224 Pistol",
  "Mabinogion",
  "Lady's Elegance",
  "Secretary on Record",
  "Fancy Light",
  "Clifftop Bloom",
  "Spring Punch",
  "Proof of the Cure",
  "Quis ut Deus",
  "Molten Meg-ma!",
  "Valkyrie Service Pistol No.17",
  "Purifying Touch",
  "Time of Secrecy",
  "Royal Blend",
  "Mulli-Gun",
  "The Lead Strategist's Expertise",
  "Shooting☆Star",
  "Learn the Old, Know the New",
  "Wise Dragon, White Tiger",
  "Torch of Steel",
  "Creative...Anguish!",
  "Library Rule #7",
  "Professor K",
  "Red Dragon",
  "Red Rector",
  "Gunbolt",
  "Mental Pointer",
  "Bullet Swinger",
  "Hyakkaryouran Rifle - A Girl's Determination",
  "Hyakkaryouran Rifle - Blazing Youth",
  "Hyakkaryouran Rifle - Keen Wisdom",
  "Multi-Tactical",
  "Yay, Bang Bang!",
  "The Honored One",
  "Festival Fever",
  "Chocolate & Strawberry",
  "Black Fang 465",
  "Clear Mirror, Serene Water",
  "Know Thyself, Know Thy Enemy",
  "Camera Blitz",
  "NK Delta",
  "Keen Illumination",
  "Policy Maker",
  "Moon Shot!",
  "Ticket Punch",
  "Dead Girl's Switch",
  "Hasty Expectations",
  "Hundred Lotus",
  "Wolf in Sheep's Clothing",
  "Arcane Magic Wand",
  "Trismegistus",
  "Kivotos Typewriter",
  "Gentle Suggestion",
  "Portable Drilling Machine",
  "Shooting☆Star",
  "Safety",
  "Pinch Hitter",
  "Anomoios",
  "Shvibzik",
  "Pravda",
  "Search & Recon",
  "Supernova: Abi-Eshuh's Sword of Light",
  "Luminous Nova",
  "Multi-Tactical Finisher",
  "Gizmo",
  "Self-Defense Sewing Gun",
  "FOX 870-Shotgun",
  "FOX 45-Submachine Gun",
  "FOX 82-Sniper Rifle",
  "Jung Leopard",
];

/** A kind's table, unscrambled: an entry per picture, or none. */
export function readPictureTable(scrambled: string): string[] {
  return (reveal(scrambled) ?? "").split(",").filter(Boolean);
}
