import type { IconType } from "react-icons";
import {
  IoBarChart,
  IoBook,
  IoCalendar,
  IoCamera,
  IoChatbubbles,
  IoColorPalette,
  IoDisc,
  IoEarth,
  IoFlag,
  IoFlash,
  IoGameController,
  IoGift,
  IoGrid,
  IoHeart,
  IoHome,
  IoIdCard,
  IoImage,
  IoKey,
  IoKeypad,
  IoLibrary,
  IoMap,
  IoMic,
  IoMoon,
  IoMusicalNotes,
  IoNavigate,
  IoPeople,
  IoPerson,
  IoPersonAdd,
  IoRadio,
  IoRibbon,
  IoRocket,
  IoSave,
  IoSchool,
  IoSearch,
  IoSettings,
  IoShieldCheckmark,
  IoSnow,
  IoSparkles,
  IoStar,
  IoStopwatch,
  IoSunny,
  IoTrophy,
} from "react-icons/io5";

/**
 * The icons content files may name (src/content/whats-new.json), by their
 * react-icons name. A short list rather than every icon, which would put
 * them all in the page; to use another, add it here (see
 * https://react-icons.github.io/react-icons/icons/io5/).
 */
export const ICONS: Record<string, IconType> = {
  IoBarChart,
  IoBook,
  IoCalendar,
  IoCamera,
  IoChatbubbles,
  IoColorPalette,
  IoDisc,
  IoEarth,
  IoFlag,
  IoFlash,
  IoGameController,
  IoGift,
  IoGrid,
  IoHeart,
  IoHome,
  IoIdCard,
  IoImage,
  IoKey,
  IoKeypad,
  IoLibrary,
  IoMap,
  IoMic,
  IoMoon,
  IoMusicalNotes,
  IoNavigate,
  IoPeople,
  IoPerson,
  IoPersonAdd,
  IoRadio,
  IoRibbon,
  IoRocket,
  IoSave,
  IoSchool,
  IoSearch,
  IoSettings,
  IoShieldCheckmark,
  IoSnow,
  IoSparkles,
  IoStar,
  IoStopwatch,
  IoSunny,
  IoTrophy,
};

/** An icon by name, or the sparkles for one not on the list. */
export function iconNamed(name: string): IconType {
  return ICONS[name] ?? IoSparkles;
}
