import { Student } from "../types/student";

/**
 * Every student and costume out on Global, in release order, copied from
 * SchaleDB. The icon sheet (see studentIcons.ts) holds their icons in the
 * same order.
 *
 * GENERATED FILE - do not edit by hand. Run `npm run students`.
 */
export const students: Student[] = [
  {
    id: 10000,
    name: "Aru",
    fullName: "Rikuhachima Aru",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 4,
    order: 0,
    height: 160,
    birthday: [3, 12],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10001,
    name: "Eimi",
    fullName: "Izumimoto Eimi",
    lore: true,
    school: "Millennium",
    role: "Tank",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 1,
    height: 167,
    birthday: [5, 1],
    year: "1st Year",
    club: "Super Phenomenon Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10002,
    name: "Haruna",
    fullName: "Kurodate Haruna",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 4,
    order: 2,
    height: 163,
    birthday: [3, 1],
    year: "3rd Year",
    club: "Gourmet Research Society",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 10003,
    name: "Hifumi",
    fullName: "Ajitani Hifumi",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Piercing",
    weapon: "AR",
    exCost: 5,
    order: 3,
    height: 158,
    birthday: [11, 27],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10004,
    name: "Hina",
    fullName: "Sorasaki Hina",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 7,
    order: 4,
    height: 142,
    birthday: [2, 19],
    year: "3rd Year",
    club: "Prefect Team",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10005,
    name: "Hoshino",
    fullName: "Takanashi Hoshino",
    lore: true,
    school: "Abydos",
    role: "Tank",
    damage: "Piercing",
    weapon: "SG",
    exCost: 4,
    order: 5,
    height: 145,
    birthday: [1, 2],
    year: "3rd Year",
    club: "Foreclosure Task Force",
    gifts: ["Lace Pillow", "Antique Egg Handicraft"],
  },
  {
    id: 10006,
    name: "Iori",
    fullName: "Shiromi Iori",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 3,
    order: 6,
    height: 157,
    birthday: [11, 8],
    year: "2nd Year",
    club: "Prefect Team",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10007,
    name: "Maki",
    fullName: "Konuri Maki",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "MG",
    exCost: 5,
    order: 7,
    height: 149,
    birthday: [8, 1],
    year: "1st Year",
    club: "Veritas",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10008,
    name: "Neru",
    fullName: "Mikamo Neru",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 2,
    order: 8,
    height: 146,
    birthday: [8, 17],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10009,
    name: "Izumi",
    fullName: "Shishidou Izumi",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 3,
    order: 9,
    height: 161,
    birthday: [5, 11],
    year: "2nd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10010,
    name: "Shiroko",
    fullName: "Sunaookami Shiroko",
    lore: true,
    school: "Abydos",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 2,
    order: 10,
    height: 156,
    birthday: [5, 16],
    year: "2nd Year",
    club: "Foreclosure Task Force",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10011,
    name: "Shun",
    fullName: "Sunohara Shun",
    lore: true,
    school: "Shanhaijing",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 3,
    order: 11,
    height: 174,
    birthday: [2, 5],
    year: "3rd Year",
    club: "Plum Blossom Garden",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10012,
    name: "Sumire",
    fullName: "Otohana Sumire",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SG",
    exCost: 3,
    order: 12,
    height: 167,
    birthday: [8, 20],
    year: "2nd Year",
    club: "Athletics Training Club",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10013,
    name: "Tsurugi",
    fullName: "Kenzaki Tsurugi",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SG",
    exCost: 3,
    order: 13,
    height: 162,
    birthday: [6, 24],
    year: "3rd Year",
    club: "Justice Task Force",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 13000,
    name: "Akane",
    fullName: "Murokasa Akane",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 2,
    order: 14,
    height: 164,
    birthday: [4, 1],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 13001,
    name: "Chise",
    fullName: "Waraku Chise",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "GL",
    exCost: 4,
    order: 15,
    height: 159,
    birthday: [7, 13],
    year: "2nd Year",
    club: "Yin-Yang Club",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 13002,
    name: "Akari",
    fullName: "Wanibuchi Akari",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 16,
    height: 167,
    birthday: [12, 9],
    year: "3rd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 13003,
    name: "Hasumi",
    fullName: "Hanekawa Hasumi",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 5,
    order: 17,
    height: 179,
    birthday: [12, 12],
    year: "3rd Year",
    club: "Justice Task Force",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 13004,
    name: "Nonomi",
    fullName: "Izayoi Nonomi",
    lore: true,
    school: "Abydos",
    role: "Dealer",
    damage: "Piercing",
    weapon: "MG",
    exCost: 5,
    order: 18,
    height: 160,
    birthday: [9, 1],
    year: "2nd Year",
    club: "Foreclosure Task Force",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 13005,
    name: "Kayoko",
    fullName: "Onikata Kayoko",
    lore: true,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 6,
    order: 19,
    height: 157,
    birthday: [3, 17],
    year: "3rd Year",
    club: "Problem Solver 68",
    gifts: ["Airbook Rare"],
  },
  {
    id: 13006,
    name: "Mutsuki",
    fullName: "Asagi Mutsuki",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 4,
    order: 20,
    height: 144,
    birthday: [7, 29],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 13007,
    name: "Junko",
    fullName: "Akashi Junko",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 5,
    order: 21,
    height: 149,
    birthday: [12, 27],
    year: "1st Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 13008,
    name: "Serika",
    fullName: "Kuromi Serika",
    lore: true,
    school: "Abydos",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 2,
    order: 22,
    height: 153,
    birthday: [6, 25],
    year: "1st Year",
    club: "Foreclosure Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 13009,
    name: "Tsubaki",
    fullName: "Kasuga Tsubaki",
    lore: true,
    school: "Hyakkiyako",
    role: "Tank",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 4,
    order: 23,
    height: 162,
    birthday: [2, 3],
    year: "2nd Year",
    club: "Inner Discipline Club",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 13010,
    name: "Yuuka",
    fullName: "Hayase Yuuka",
    lore: true,
    school: "Millennium",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 3,
    order: 24,
    height: 156,
    birthday: [3, 14],
    year: "2nd Year",
    club: "Seminar",
    gifts: ["Airbook Rare", "Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 16000,
    name: "Haruka",
    fullName: "Igusa Haruka",
    lore: true,
    school: "Gehenna",
    role: "Tank",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 25,
    height: 157,
    birthday: [5, 13],
    year: "1st Year",
    club: "Problem Solver 68",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 16001,
    name: "Asuna",
    fullName: "Ichinose Asuna",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 2,
    order: 26,
    height: 167,
    birthday: [3, 24],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 16002,
    name: "Kotori",
    fullName: "Toyomi Kotori",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "MG",
    exCost: 4,
    order: 27,
    height: 151,
    birthday: [12, 31],
    year: "1st Year",
    club: "Engineering Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 16003,
    name: "Suzumi",
    fullName: "Morizuki Suzumi",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 28,
    height: 162,
    birthday: [8, 31],
    year: "2nd Year",
    club: "Trinity's Vigilante Crew",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 16004,
    name: "Pina",
    fullName: "Asahina Pina",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Piercing",
    weapon: "MG",
    exCost: 4,
    order: 29,
    height: 165,
    birthday: [11, 3],
    year: "1st Year",
    club: "Festival Operations Department",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20000,
    name: "Hibiki",
    fullName: "Nekozuka Hibiki",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MT",
    exCost: 4,
    order: 30,
    height: 154,
    birthday: [4, 2],
    year: "1st Year",
    club: "Engineering Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20001,
    name: "Karin",
    fullName: "Kakudate Karin",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 4,
    order: 31,
    height: 170,
    birthday: [2, 2],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20002,
    name: "Saya",
    fullName: "Yakushi Saya",
    lore: true,
    school: "Shanhaijing",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 6,
    order: 32,
    height: 149,
    birthday: [1, 3],
    year: "2nd Year",
    club: "Eastern Alchemy Society",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 23000,
    name: "Airi",
    fullName: "Kurimura Airi",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 5,
    order: 33,
    height: 160,
    birthday: [1, 30],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 23001,
    name: "Fuuka",
    fullName: "Aikiyo Fuuka",
    lore: true,
    school: "Gehenna",
    role: "Healer",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 5,
    order: 34,
    height: 159,
    birthday: [4, 30],
    year: "2nd Year",
    club: "School Lunch Club",
    gifts: ["Sewing Kit"],
  },
  {
    id: 23002,
    name: "Hanae",
    fullName: "Asagao Hanae",
    lore: true,
    school: "Trinity",
    role: "Healer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 35,
    height: 150,
    birthday: [5, 12],
    year: "1st Year",
    club: "Remedial Knights",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 23003,
    name: "Hare",
    fullName: "Omagari Hare",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 36,
    height: 153,
    birthday: [4, 19],
    year: "2nd Year",
    club: "Veritas",
    gifts: ["Airbook Rare"],
  },
  {
    id: 23004,
    name: "Utaha",
    fullName: "Shiraishi Utaha",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 4,
    order: 37,
    height: 162,
    birthday: [11, 13],
    year: "3rd Year",
    club: "Engineering Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 23005,
    name: "Ayane",
    fullName: "Okusora Ayane",
    lore: true,
    school: "Abydos",
    role: "Healer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 4,
    order: 38,
    height: 153,
    birthday: [11, 12],
    year: "1st Year",
    club: "Foreclosure Task Force",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 26000,
    name: "Chinatsu",
    fullName: "Hinomiya Chinatsu",
    lore: true,
    school: "Gehenna",
    role: "Healer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 4,
    order: 39,
    height: 159,
    birthday: [8, 22],
    year: "1st Year",
    club: "Prefect Team",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 26001,
    name: "Kotama",
    fullName: "Otose Kotama",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 40,
    height: 158,
    birthday: [1, 5],
    year: "3rd Year",
    club: "Veritas",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 26002,
    name: "Juri",
    fullName: "Ushimaki Juri",
    lore: true,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "SG",
    exCost: 3,
    order: 41,
    height: 170,
    birthday: [10, 20],
    year: "1st Year",
    club: "School Lunch Club",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 26003,
    name: "Serina",
    fullName: "Sumi Serina",
    lore: true,
    school: "Trinity",
    role: "Healer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 2,
    order: 42,
    height: 156,
    birthday: [1, 6],
    year: "2nd Year",
    club: "Remedial Knights",
    gifts: ['Samuela "The Beyond"', "Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 26004,
    name: "Shimiko",
    fullName: "Endou Shimiko",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 3,
    order: 43,
    height: 157,
    birthday: [11, 30],
    year: "1st Year",
    club: "Library Committee",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 26005,
    name: "Yoshimi",
    fullName: "Ibaragi Yoshimi",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 4,
    order: 44,
    height: 146,
    birthday: [8, 29],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 20003,
    name: "Mashiro",
    fullName: "Shizuyama Mashiro",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 3,
    order: 45,
    height: 155,
    birthday: [6, 5],
    year: "1st Year",
    club: "Justice Task Force",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10014,
    name: "Izuna",
    fullName: "Kuda Izuna",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 3,
    order: 46,
    height: 155,
    birthday: [12, 16],
    year: "1st Year",
    club: "Ninjutsu Research Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 23006,
    name: "Shizuko",
    fullName: "Kawawa Shizuko",
    lore: true,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 47,
    height: 153,
    birthday: [7, 7],
    year: "2nd Year",
    club: "Festival Operations Department",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10015,
    name: "Aris",
    fullName: "Tendou Aris",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "RG",
    exCost: 6,
    order: 48,
    height: 152,
    birthday: [3, 25],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10016,
    name: "Midori",
    fullName: "Saiba Midori",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 3,
    order: 49,
    height: 143,
    birthday: [12, 8],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 13011,
    name: "Momoi",
    fullName: "Saiba Momoi",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 3,
    order: 50,
    height: 143,
    birthday: [12, 8],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10017,
    name: "Cherino",
    fullName: "Renkawa Cherino",
    lore: true,
    school: "Red Winter",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 7,
    order: 51,
    height: 128,
    birthday: [10, 27],
    year: "3rd Year",
    club: "Red Winter Office",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 26006,
    name: "Nodoka",
    fullName: "Amami Nodoka",
    lore: true,
    school: "Red Winter",
    role: "Support",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 3,
    order: 52,
    height: 147,
    birthday: [2, 20],
    year: "2nd Year",
    club: "Spec Ops No. 227",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10018,
    name: "Yuzu",
    fullName: "Hanaoka Yuzu",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "GL",
    exCost: 4,
    order: 53,
    height: 150,
    birthday: [8, 12],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10019,
    name: "Azusa",
    fullName: "Shirasu Azusa",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 5,
    order: 54,
    height: 149,
    birthday: [12, 26],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 23007,
    name: "Hanako",
    fullName: "Urawa Hanako",
    lore: true,
    school: "Trinity",
    role: "Healer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 5,
    order: 55,
    height: 161,
    birthday: [1, 3],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10020,
    name: "Koharu",
    fullName: "Shimoe Koharu",
    lore: true,
    school: "Trinity",
    role: "Healer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 3,
    order: 56,
    height: 148,
    birthday: [4, 16],
    year: "1st Year",
    club: "Make-Up Work Club",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10021,
    name: "Azusa (Swimsuit)",
    fullName: "Shirasu Azusa",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 5,
    order: 57,
    height: 149,
    birthday: [12, 26],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20004,
    name: "Mashiro (Swimsuit)",
    fullName: "Shizuyama Mashiro",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 4,
    order: 58,
    height: 155,
    birthday: [6, 5],
    year: "1st Year",
    club: "Justice Task Force",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 16005,
    name: "Tsurugi (Swimsuit)",
    fullName: "Kenzaki Tsurugi",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 59,
    height: 162,
    birthday: [6, 24],
    year: "3rd Year",
    club: "Justice Task Force",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20005,
    name: "Hifumi (Swimsuit)",
    fullName: "Ajitani Hifumi",
    lore: false,
    school: "Trinity",
    role: "T.S.",
    damage: "Piercing",
    weapon: "AR",
    exCost: 10,
    order: 60,
    height: 158,
    birthday: [11, 27],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10022,
    name: "Hina (Swimsuit)",
    fullName: "Sorasaki Hina",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 3,
    order: 61,
    height: 142,
    birthday: [2, 19],
    year: "3rd Year",
    club: "Prefect Team",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10023,
    name: "Iori (Swimsuit)",
    fullName: "Shiromi Iori",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 4,
    order: 62,
    height: 157,
    birthday: [11, 8],
    year: "2nd Year",
    club: "Prefect Team",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 16006,
    name: "Izumi (Swimsuit)",
    fullName: "Shishidou Izumi",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "MG",
    exCost: 4,
    order: 63,
    height: 161,
    birthday: [5, 11],
    year: "2nd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10024,
    name: "Shiroko (Cycling)",
    fullName: "Sunaookami Shiroko",
    lore: false,
    school: "Abydos",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 4,
    order: 64,
    height: 156,
    birthday: [5, 16],
    year: "2nd Year",
    club: "Foreclosure Task Force",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10025,
    name: "Shun (Small)",
    fullName: "Sunohara Shun",
    lore: false,
    school: "Shanhaijing",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 5,
    order: 65,
    height: null,
    birthday: [2, 5],
    year: "3rd Year",
    club: "Plum Blossom Garden",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 13012,
    name: "Kirino",
    fullName: "Nakatsukasa Kirino",
    lore: true,
    school: "Valkyrie",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 66,
    height: 161,
    birthday: [10, 22],
    year: "1st Year",
    club: "Public Safety Bureau",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 20006,
    name: "Saya (Casual)",
    fullName: "Yakushi Saya",
    lore: false,
    school: "Shanhaijing",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 5,
    order: 67,
    height: 149,
    birthday: [1, 3],
    year: "2nd Year",
    club: "Eastern Alchemy Society",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10026,
    name: "Neru (Bunny)",
    fullName: "Mikamo Neru",
    lore: false,
    school: "Millennium",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 4,
    order: 68,
    height: 146,
    birthday: [8, 17],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10027,
    name: "Karin (Bunny)",
    fullName: "Kakudate Karin",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 7,
    order: 69,
    height: 170,
    birthday: [2, 2],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10028,
    name: "Asuna (Bunny)",
    fullName: "Ichinose Asuna",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "AR",
    exCost: 5,
    order: 70,
    height: 167,
    birthday: [3, 24],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10029,
    name: "Natsu",
    fullName: "Yutori Natsu",
    lore: true,
    school: "Trinity",
    role: "Tank",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 3,
    order: 71,
    height: 152,
    birthday: [12, 4],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 23008,
    name: "Mari",
    fullName: "Iochi Mari",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 2,
    order: 72,
    height: 151,
    birthday: [9, 12],
    year: "1st Year",
    club: "The Sisterhood",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 20007,
    name: "Hatsune Miku",
    fullName: "Hatsune Miku",
    lore: true,
    school: "Etc.",
    role: "Support",
    damage: "Explosive",
    weapon: "GL",
    exCost: 5,
    order: 73,
    height: 158,
    birthday: [8, 31],
    year: "Unknown",
    club: "None",
    gifts: [],
  },
  {
    id: 20008,
    name: "Ako",
    fullName: "Amau Ako",
    lore: true,
    school: "Gehenna",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 74,
    height: 165,
    birthday: [12, 22],
    year: "3rd Year",
    club: "Prefect Team",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 20009,
    name: "Cherino (Hot Spring)",
    fullName: "Renkawa Cherino",
    lore: false,
    school: "Red Winter",
    role: "T.S.",
    damage: "Explosive",
    weapon: "HG",
    exCost: 6,
    order: 75,
    height: 128,
    birthday: [10, 27],
    year: "3rd Year",
    club: "Red Winter Office",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10030,
    name: "Chinatsu (Hot Spring)",
    fullName: "Hinomiya Chinatsu",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 2,
    order: 76,
    height: 159,
    birthday: [8, 22],
    year: "1st Year",
    club: "Prefect Team",
    gifts: ["Streets of Thugs Vol. 1", "Antique Egg Handicraft"],
  },
  {
    id: 16007,
    name: "Tomoe",
    fullName: "Sashiro Tomoe",
    lore: true,
    school: "Red Winter",
    role: "Support",
    damage: "Piercing",
    weapon: "SR",
    exCost: 3,
    order: 77,
    height: 165,
    birthday: [11, 10],
    year: "3rd Year",
    club: "Red Winter Office",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 20010,
    name: "Nodoka (Hot Spring)",
    fullName: "Amami Nodoka",
    lore: false,
    school: "Red Winter",
    role: "Healer",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 4,
    order: 78,
    height: 147,
    birthday: [2, 20],
    year: "2nd Year",
    club: "Spec Ops No. 227",
    gifts: ["Mille-Feuille Traditional Parfait", "Music Concert Ticket"],
  },
  {
    id: 10031,
    name: "Aru (New Year)",
    fullName: "Rikuhachima Aru",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 6,
    order: 79,
    height: 160,
    birthday: [3, 12],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10032,
    name: "Mutsuki (New Year)",
    fullName: "Asagi Mutsuki",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Mystic",
    weapon: "MG",
    exCost: 2,
    order: 80,
    height: 144,
    birthday: [7, 29],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20011,
    name: "Serika (New Year)",
    fullName: "Kuromi Serika",
    lore: false,
    school: "Abydos",
    role: "Support",
    damage: "Piercing",
    weapon: "AR",
    exCost: 3,
    order: 81,
    height: 153,
    birthday: [6, 25],
    year: "1st Year",
    club: "Foreclosure Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10033,
    name: "Wakamo",
    fullName: "Kosaka Wakamo",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 4,
    order: 82,
    height: 161,
    birthday: [4, 3],
    year: "Suspended",
    club: "None",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 16008,
    name: "Fubuki",
    fullName: "Nemugaki Fubuki",
    lore: true,
    school: "Valkyrie",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 4,
    order: 83,
    height: 148,
    birthday: [10, 21],
    year: "1st Year",
    club: "Public Safety Bureau",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 20012,
    name: "Sena",
    fullName: "Himuro Sena",
    lore: true,
    school: "Gehenna",
    role: "T.S.",
    damage: "Mystic",
    weapon: "GL",
    exCost: 5,
    order: 84,
    height: 155,
    birthday: [4, 7],
    year: "3rd Year",
    club: "Medical Emergency Club",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 20013,
    name: "Chihiro",
    fullName: "Kagami Chihiro",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 3,
    order: 85,
    height: 160,
    birthday: [4, 26],
    year: "3rd Year",
    club: "Veritas",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10034,
    name: "Mimori",
    fullName: "Mizuha Mimori",
    lore: true,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 86,
    height: 156,
    birthday: [3, 15],
    year: "2nd Year",
    club: "Inner Discipline Club",
    gifts: ["Sophisticated Hairbrush", "Sewing Kit"],
  },
  {
    id: 10035,
    name: "Ui",
    fullName: "Kozeki Ui",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Explosive",
    weapon: "SR",
    exCost: 5,
    order: 87,
    height: 165,
    birthday: [4, 23],
    year: "3rd Year",
    club: "Library Committee",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10036,
    name: "Hinata",
    fullName: "Wakaba Hinata",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "HG",
    exCost: 6,
    order: 88,
    height: 166,
    birthday: [5, 17],
    year: "3rd Year",
    club: "The Sisterhood",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10037,
    name: "Marina",
    fullName: "Ikekura Marina",
    lore: true,
    school: "Red Winter",
    role: "Tank",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 3,
    order: 89,
    height: 166,
    birthday: [11, 4],
    year: "2nd Year",
    club: "Red Winter Office",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10038,
    name: "Miyako",
    fullName: "Tsukiyuki Miyako",
    lore: true,
    school: "SRT",
    role: "Tank",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 3,
    order: 90,
    height: 156,
    birthday: [1, 7],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20014,
    name: "Saki",
    fullName: "Sorai Saki",
    lore: true,
    school: "SRT",
    role: "Dealer",
    damage: "Piercing",
    weapon: "MG",
    exCost: 4,
    order: 91,
    height: 161,
    birthday: [4, 9],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10039,
    name: "Miyu",
    fullName: "Kasumizawa Miyu",
    lore: true,
    school: "SRT",
    role: "Support",
    damage: "Piercing",
    weapon: "SR",
    exCost: 3,
    order: 92,
    height: 149,
    birthday: [7, 12],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20015,
    name: "Kaede",
    fullName: "Isami Kaede",
    lore: true,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 4,
    order: 93,
    height: 142,
    birthday: [7, 9],
    year: "1st Year",
    club: "Inner Discipline Club",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20016,
    name: "Iroha",
    fullName: "Natsume Iroha",
    lore: true,
    school: "Gehenna",
    role: "T.S.",
    damage: "Mystic",
    weapon: "HG",
    exCost: 8,
    order: 94,
    height: 151,
    birthday: [11, 16],
    year: "2nd Year",
    club: "Pandemonium Society",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 16009,
    name: "Michiru",
    fullName: "Chidori Michiru",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SG",
    exCost: 5,
    order: 95,
    height: 153,
    birthday: [2, 22],
    year: "3rd Year",
    club: "Ninjutsu Research Club",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10040,
    name: "Tsukuyo",
    fullName: "Ono Tsukuyo",
    lore: true,
    school: "Hyakkiyako",
    role: "Tank",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 3,
    order: 96,
    height: 180,
    birthday: [4, 5],
    year: "1st Year",
    club: "Ninjutsu Research Club",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 10041,
    name: "Misaki",
    fullName: "Imashino Misaki",
    lore: true,
    school: "Arius",
    role: "Dealer",
    damage: "Explosive",
    weapon: "RL",
    exCost: 5,
    order: 97,
    height: 163,
    birthday: [1, 13],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Lace Pillow"],
  },
  {
    id: 20017,
    name: "Hiyori",
    fullName: "Tsuchinaga Hiyori",
    lore: true,
    school: "Arius",
    role: "Support",
    damage: "Explosive",
    weapon: "SR",
    exCost: 3,
    order: 98,
    height: 155,
    birthday: [1, 8],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10042,
    name: "Atsuko",
    fullName: "Hakari Atsuko",
    lore: true,
    school: "Arius",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 4,
    order: 99,
    height: 158,
    birthday: [1, 20],
    year: "1st Year",
    club: "Arius Squad",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10043,
    name: "Wakamo (Swimsuit)",
    fullName: "Kosaka Wakamo",
    lore: false,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 5,
    order: 100,
    height: 161,
    birthday: [4, 3],
    year: "Suspended",
    club: "None",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10044,
    name: "Nonomi (Swimsuit)",
    fullName: "Izayoi Nonomi",
    lore: false,
    school: "Abydos",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 6,
    order: 101,
    height: 160,
    birthday: [9, 1],
    year: "2nd Year",
    club: "Foreclosure Task Force",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 26007,
    name: "Ayane (Swimsuit)",
    fullName: "Okusora Ayane",
    lore: false,
    school: "Abydos",
    role: "T.S.",
    damage: "Piercing",
    weapon: "HG",
    exCost: 4,
    order: 102,
    height: 153,
    birthday: [11, 12],
    year: "1st Year",
    club: "Foreclosure Task Force",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10045,
    name: "Hoshino (Swimsuit)",
    fullName: "Takanashi Hoshino",
    lore: false,
    school: "Abydos",
    role: "Support",
    damage: "Explosive",
    weapon: "SG",
    exCost: 6,
    order: 103,
    height: 145,
    birthday: [1, 2],
    year: "3rd Year",
    club: "Foreclosure Task Force",
    gifts: ["Lace Pillow", "Antique Egg Handicraft"],
  },
  {
    id: 26008,
    name: "Shizuko (Swimsuit)",
    fullName: "Kawawa Shizuko",
    lore: false,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 104,
    height: 153,
    birthday: [7, 7],
    year: "2nd Year",
    club: "Festival Operations Department",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10046,
    name: "Izuna (Swimsuit)",
    fullName: "Kuda Izuna",
    lore: false,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 2,
    order: 105,
    height: 155,
    birthday: [12, 16],
    year: "1st Year",
    club: "Ninjutsu Research Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10047,
    name: "Chise (Swimsuit)",
    fullName: "Waraku Chise",
    lore: false,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Mystic",
    weapon: "GL",
    exCost: 6,
    order: 106,
    height: 159,
    birthday: [7, 13],
    year: "2nd Year",
    club: "Yin-Yang Club",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10048,
    name: "Saori",
    fullName: "Joumae Saori",
    lore: true,
    school: "Arius",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 107,
    height: 167,
    birthday: [9, 3],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 20018,
    name: "Moe",
    fullName: "Kazekura Moe",
    lore: true,
    school: "SRT",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 4,
    order: 108,
    height: 163,
    birthday: [9, 13],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10049,
    name: "Kazusa",
    fullName: "Kyoyama Kazusa",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "MG",
    exCost: 4,
    order: 109,
    height: 155,
    birthday: [8, 5],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10050,
    name: "Kokona",
    fullName: "Sunohara Kokona",
    lore: true,
    school: "Shanhaijing",
    role: "Healer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 2,
    order: 110,
    height: 139,
    birthday: [6, 1],
    year: "1st Year",
    club: "Plum Blossom Garden",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10051,
    name: "Utaha (Cheer Squad)",
    fullName: "Shiraishi Utaha",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 5,
    order: 111,
    height: 162,
    birthday: [11, 13],
    year: "3rd Year",
    club: "Engineering Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10052,
    name: "Noa",
    fullName: "Ushio Noa",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 112,
    height: 161,
    birthday: [4, 13],
    year: "2nd Year",
    club: "Seminar",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 16010,
    name: "Hibiki (Cheer Squad)",
    fullName: "Nekozuka Hibiki",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MT",
    exCost: 7,
    order: 113,
    height: 154,
    birthday: [4, 2],
    year: "1st Year",
    club: "Engineering Department",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20019,
    name: "Akane (Bunny)",
    fullName: "Murokasa Akane",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 114,
    height: 164,
    birthday: [4, 1],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10053,
    name: "Yuuka (Track)",
    fullName: "Hayase Yuuka",
    lore: false,
    school: "Millennium",
    role: "Tank",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 3,
    order: 115,
    height: 156,
    birthday: [3, 14],
    year: "2nd Year",
    club: "Seminar",
    gifts: [],
  },
  {
    id: 10054,
    name: "Mari (Track)",
    fullName: "Iochi Mari",
    lore: false,
    school: "Trinity",
    role: "Healer",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 116,
    height: 151,
    birthday: [9, 12],
    year: "1st Year",
    club: "The Sisterhood",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 16011,
    name: "Hasumi (Track)",
    fullName: "Hanekawa Hasumi",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 3,
    order: 117,
    height: 179,
    birthday: [12, 12],
    year: "3rd Year",
    club: "Justice Task Force",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 20020,
    name: "Himari",
    fullName: "Akeboshi Himari",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 118,
    height: 162,
    birthday: [12, 10],
    year: "3rd Year",
    club: "Super Phenomenon Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10055,
    name: "Shigure",
    fullName: "Mayoi Shigure",
    lore: true,
    school: "Red Winter",
    role: "Dealer",
    damage: "Explosive",
    weapon: "GL",
    exCost: 5,
    order: 119,
    height: 156,
    birthday: [1, 22],
    year: "2nd Year",
    club: "Spec Ops No. 227",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10056,
    name: "Serina (Christmas)",
    fullName: "Sumi Serina",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Piercing",
    weapon: "AR",
    exCost: 4,
    order: 120,
    height: 156,
    birthday: [1, 6],
    year: "2nd Year",
    club: "Remedial Knights",
    gifts: ["Lace Pillow"],
  },
  {
    id: 20021,
    name: "Hanae (Christmas)",
    fullName: "Asagao Hanae",
    lore: false,
    school: "Trinity",
    role: "Healer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 5,
    order: 121,
    height: 150,
    birthday: [5, 12],
    year: "1st Year",
    club: "Remedial Knights",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10057,
    name: "Haruna (New Year)",
    fullName: "Kurodate Haruna",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 5,
    order: 122,
    height: 163,
    birthday: [3, 1],
    year: "3rd Year",
    club: "Gourmet Research Society",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 20022,
    name: "Fuuka (New Year)",
    fullName: "Aikiyo Fuuka",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 3,
    order: 123,
    height: 159,
    birthday: [4, 30],
    year: "2nd Year",
    club: "School Lunch Club",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 16012,
    name: "Junko (New Year)",
    fullName: "Akashi Junko",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 2,
    order: 124,
    height: 149,
    birthday: [12, 27],
    year: "1st Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10058,
    name: "Mine",
    fullName: "Aomori Mine",
    lore: true,
    school: "Trinity",
    role: "Tank",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 125,
    height: 168,
    birthday: [11, 23],
    year: "3rd Year",
    club: "Remedial Knights",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10059,
    name: "Mika",
    fullName: "Misono Mika",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 6,
    order: 126,
    height: 157,
    birthday: [5, 8],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10060,
    name: "Megu",
    fullName: "Shimokura Megu",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "FT",
    exCost: 5,
    order: 127,
    height: 164,
    birthday: [4, 25],
    year: "3rd Year",
    club: "Hot Springs Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20023,
    name: "Kanna",
    fullName: "Ogata Kanna",
    lore: true,
    school: "Valkyrie",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 128,
    height: 166,
    birthday: [9, 7],
    year: "3rd Year",
    club: "Public Peace Bureau",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10061,
    name: "Sakurako",
    fullName: "Utazumi Sakurako",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 4,
    order: 129,
    height: 160,
    birthday: [10, 4],
    year: "3rd Year",
    club: "The Sisterhood",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10062,
    name: "Toki",
    fullName: "Asuma Toki",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 2,
    order: 130,
    height: 165,
    birthday: [8, 16],
    year: "1st Year",
    club: "Cleaning & Clearing",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 20024,
    name: "Nagisa",
    fullName: "Kirifuji Nagisa",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 131,
    height: 160,
    birthday: [7, 4],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10063,
    name: "Koyuki",
    fullName: "Kurosaki Koyuki",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "MG",
    exCost: 4,
    order: 132,
    height: 149,
    birthday: [2, 14],
    year: "1st Year",
    club: "Seminar",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10064,
    name: "Kayoko (New Year)",
    fullName: "Onikata Kayoko",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 2,
    order: 133,
    height: 157,
    birthday: [3, 17],
    year: "3rd Year",
    club: "Problem Solver 68",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 20025,
    name: "Haruka (New Year)",
    fullName: "Igusa Haruka",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 134,
    height: 157,
    birthday: [5, 13],
    year: "1st Year",
    club: "Problem Solver 68",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 10065,
    name: "Kaho",
    fullName: "Kuwakami Kaho",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 5,
    order: 135,
    height: 173,
    birthday: [10, 9],
    year: "3rd Year",
    club: "Yin-Yang Club",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10066,
    name: "Aris (Maid)",
    fullName: "Tendou Aris",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "RG",
    exCost: 4,
    order: 136,
    height: 152,
    birthday: [3, 25],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ["Sophisticated Hairbrush", 'Board Game "The Life"'],
  },
  {
    id: 10067,
    name: "Toki (Bunny)",
    fullName: "Asuma Toki",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 2,
    order: 137,
    height: 165,
    birthday: [8, 16],
    year: "1st Year",
    club: "Cleaning & Clearing",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 26009,
    name: "Yuzu (Maid)",
    fullName: "Hanaoka Yuzu",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "GL",
    exCost: 5,
    order: 138,
    height: 150,
    birthday: [8, 12],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10068,
    name: "Reisa",
    fullName: "Uzawa Reisa",
    lore: true,
    school: "Trinity",
    role: "Tank",
    damage: "Piercing",
    weapon: "SG",
    exCost: 3,
    order: 139,
    height: 153,
    birthday: [5, 31],
    year: "1st Year",
    club: "Trinity's Vigilante Crew",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10069,
    name: "Rumi",
    fullName: "Akeshiro Rumi",
    lore: true,
    school: "Shanhaijing",
    role: "Healer",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 4,
    order: 140,
    height: 168,
    birthday: [3, 5],
    year: "3rd Year",
    club: "Black Tortoise Promenade",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10070,
    name: "Mina",
    fullName: "Konoe Mina",
    lore: true,
    school: "Shanhaijing",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 141,
    height: 166,
    birthday: [9, 9],
    year: "2nd Year",
    club: "Genryumon",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 20026,
    name: "Minori",
    fullName: "Yasumori Minori",
    lore: true,
    school: "Red Winter",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 4,
    order: 142,
    height: 158,
    birthday: [7, 14],
    year: "3rd Year",
    club: "Labor Party",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10071,
    name: "Miyako (Swimsuit)",
    fullName: "Tsukiyuki Miyako",
    lore: false,
    school: "SRT",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 2,
    order: 143,
    height: 156,
    birthday: [1, 7],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10072,
    name: "Saki (Swimsuit)",
    fullName: "Sorai Saki",
    lore: false,
    school: "SRT",
    role: "Support",
    damage: "Explosive",
    weapon: "MG",
    exCost: 4,
    order: 144,
    height: 161,
    birthday: [4, 9],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 26010,
    name: "Miyu (Swimsuit)",
    fullName: "Kasumizawa Miyu",
    lore: false,
    school: "SRT",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 5,
    order: 145,
    height: 149,
    birthday: [7, 12],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20027,
    name: "Shiroko (Swimsuit)",
    fullName: "Sunaookami Shiroko",
    lore: false,
    school: "Abydos",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 3,
    order: 146,
    height: 156,
    birthday: [5, 16],
    year: "2nd Year",
    club: "Foreclosure Task Force",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10073,
    name: "Ui (Swimsuit)",
    fullName: "Kozeki Ui",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Piercing",
    weapon: "SR",
    exCost: 4,
    order: 147,
    height: 165,
    birthday: [4, 23],
    year: "3rd Year",
    club: "Library Committee",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 20028,
    name: "Hinata (Swimsuit)",
    fullName: "Wakaba Hinata",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 6,
    order: 148,
    height: 166,
    birthday: [5, 17],
    year: "3rd Year",
    club: "The Sisterhood",
    gifts: ["Sewing Kit"],
  },
  {
    id: 16013,
    name: "Koharu (Swimsuit)",
    fullName: "Shimoe Koharu",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Mystic",
    weapon: "SR",
    exCost: 3,
    order: 149,
    height: 148,
    birthday: [4, 16],
    year: "1st Year",
    club: "Make-Up Work Club",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10074,
    name: "Hanako (Swimsuit)",
    fullName: "Urawa Hanako",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 2,
    order: 150,
    height: 161,
    birthday: [1, 3],
    year: "2nd Year",
    club: "Make-Up Work Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20029,
    name: "Mimori (Swimsuit)",
    fullName: "Mizuha Mimori",
    lore: false,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 3,
    order: 151,
    height: 156,
    birthday: [3, 15],
    year: "2nd Year",
    club: "Inner Discipline Club",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10075,
    name: "Meru",
    fullName: "Himeki Meru",
    lore: true,
    school: "Red Winter",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 5,
    order: 152,
    height: 137,
    birthday: [12, 21],
    year: "2nd Year",
    club: "Knowledge Liberation Front",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 13013,
    name: "Momiji",
    fullName: "Akiizumi Momiji",
    lore: true,
    school: "Red Winter",
    role: "Dealer",
    damage: "Sonic",
    weapon: "RL",
    exCost: 4,
    order: 153,
    height: 135,
    birthday: [8, 7],
    year: "1st Year",
    club: "Knowledge Liberation Front",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10076,
    name: "Kotori (Cheer Squad)",
    fullName: "Toyomi Kotori",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 3,
    order: 154,
    height: 151,
    birthday: [12, 31],
    year: "1st Year",
    club: "Engineering Department",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 20030,
    name: "Haruna (Track)",
    fullName: "Kurodate Haruna",
    lore: false,
    school: "Gehenna",
    role: "Healer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 3,
    order: 155,
    height: 163,
    birthday: [3, 1],
    year: "3rd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10077,
    name: "Ichika",
    fullName: "Nakamasa Ichika",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 6,
    order: 156,
    height: 163,
    birthday: [11, 11],
    year: "2nd Year",
    club: "Justice Task Force",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10078,
    name: "Kasumi",
    fullName: "Kinugawa Kasumi",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Sonic",
    weapon: "HG",
    exCost: 4,
    order: 157,
    height: 148,
    birthday: [5, 24],
    year: "2nd Year",
    club: "Hot Springs Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20031,
    name: "Shigure (Hot Spring)",
    fullName: "Mayoi Shigure",
    lore: false,
    school: "Red Winter",
    role: "Healer",
    damage: "Piercing",
    weapon: "GL",
    exCost: 6,
    order: 158,
    height: 156,
    birthday: [1, 22],
    year: "2nd Year",
    club: "Spec Ops No. 227",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10079,
    name: "Misaka Mikoto",
    fullName: "Misaka Mikoto",
    lore: true,
    school: "Tokiwadai",
    role: "Dealer",
    damage: "Piercing",
    weapon: "AR",
    exCost: 3,
    order: 159,
    height: 161,
    birthday: [5, 2],
    year: "2nd Year",
    club: "None",
    gifts: [],
  },
  {
    id: 10080,
    name: "Shokuhou Misaki",
    fullName: "Shokuhou Misaki",
    lore: true,
    school: "Tokiwadai",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 5,
    order: 160,
    height: null,
    birthday: null,
    year: "2nd Year",
    club: "None",
    gifts: [],
  },
  {
    id: 26011,
    name: "Saten Ruiko",
    fullName: "Saten Ruiko",
    lore: true,
    school: "Sakugawa",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 4,
    order: 161,
    height: 160,
    birthday: null,
    year: "1st Year",
    club: "None",
    gifts: [],
  },
  {
    id: 10081,
    name: "Yukari",
    fullName: "Kadenokouji Yukari",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 7,
    order: 162,
    height: 155,
    birthday: [6, 16],
    year: "1st Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10082,
    name: "Renge",
    fullName: "Fuwa Renge",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 3,
    order: 163,
    height: 157,
    birthday: [7, 23],
    year: "2nd Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10083,
    name: "Kikyou",
    fullName: "Kiryuu Kikyou",
    lore: true,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Sonic",
    weapon: "SR",
    exCost: 5,
    order: 164,
    height: 160,
    birthday: [8, 8],
    year: "2nd Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 20032,
    name: "Eimi (Swimsuit)",
    fullName: "Izumimoto Eimi",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "SG",
    exCost: 4,
    order: 165,
    height: 167,
    birthday: [5, 1],
    year: "1st Year",
    club: "Super Phenomenon Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10084,
    name: "Kotama (Camp)",
    fullName: "Otose Kotama",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 6,
    order: 166,
    height: 158,
    birthday: [1, 5],
    year: "3rd Year",
    club: "Veritas",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10085,
    name: "Hare (Camp)",
    fullName: "Omagari Hare",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 2,
    order: 167,
    height: 153,
    birthday: [4, 19],
    year: "2nd Year",
    club: "Veritas",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10087,
    name: "Ako (Dress)",
    fullName: "Amau Ako",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 5,
    order: 168,
    height: 165,
    birthday: [12, 22],
    year: "3rd Year",
    club: "Prefect Team",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 16014,
    name: "Ibuki",
    fullName: "Tanga Ibuki",
    lore: true,
    school: "Gehenna",
    role: "Support",
    damage: "Mystic",
    weapon: "AR",
    exCost: 3,
    order: 169,
    height: 128,
    birthday: [4, 14],
    year: "1st Year",
    club: "Pandemonium Society",
    gifts: ["Mille-Feuille Traditional Parfait", 'Board Game "The Life"'],
  },
  {
    id: 20033,
    name: "Makoto",
    fullName: "Hanuma Makoto",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 6,
    order: 170,
    height: 169,
    birthday: [3, 19],
    year: "3rd Year",
    club: "Pandemonium Society",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10086,
    name: "Hina (Dress)",
    fullName: "Sorasaki Hina",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 6,
    order: 171,
    height: 142,
    birthday: [2, 19],
    year: "3rd Year",
    club: "Prefect Team",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 10088,
    name: "Kayoko (Dress)",
    fullName: "Onikata Kayoko",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 5,
    order: 172,
    height: 157,
    birthday: [3, 17],
    year: "3rd Year",
    club: "Problem Solver 68",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10089,
    name: "Aru (Dress)",
    fullName: "Rikuhachima Aru",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Piercing",
    weapon: "SR",
    exCost: 3,
    order: 173,
    height: 160,
    birthday: [3, 12],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 20034,
    name: "Akari (New Year)",
    fullName: "Wanibuchi Akari",
    lore: false,
    school: "Gehenna",
    role: "T.S.",
    damage: "Mystic",
    weapon: "AR",
    exCost: 5,
    order: 174,
    height: 167,
    birthday: [12, 9],
    year: "3rd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10090,
    name: "Umika",
    fullName: "Satohama Umika",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 3,
    order: 175,
    height: 165,
    birthday: [7, 1],
    year: "1st Year",
    club: "Festival Operations Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20035,
    name: "Tsubaki (Guide)",
    fullName: "Kasuga Tsubaki",
    lore: false,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 6,
    order: 176,
    height: 162,
    birthday: [2, 3],
    year: "2nd Year",
    club: "Inner Discipline Club",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10091,
    name: "Kazusa (Band)",
    fullName: "Kyoyama Kazusa",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 3,
    order: 177,
    height: 155,
    birthday: [8, 5],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10092,
    name: "Yoshimi (Band)",
    fullName: "Ibaragi Yoshimi",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "AR",
    exCost: 10,
    order: 178,
    height: 146,
    birthday: [8, 29],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 16015,
    name: "Airi (Band)",
    fullName: "Kurimura Airi",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 2,
    order: 179,
    height: 160,
    birthday: [1, 30],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10093,
    name: "Kirara",
    fullName: "Yozakura Kirara",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 4,
    order: 180,
    height: 159,
    birthday: [2, 24],
    year: "2nd Year",
    club: "Twinkle Twinkle Club",
    gifts: ['Samuela "The Beyond"', "Sophisticated Hairbrush"],
  },
  {
    id: 10094,
    name: "Momoi (Maid)",
    fullName: "Saiba Momoi",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 4,
    order: 181,
    height: 143,
    birthday: [12, 8],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10095,
    name: "Midori (Maid)",
    fullName: "Saiba Midori",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 5,
    order: 182,
    height: 143,
    birthday: [12, 8],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20036,
    name: "Serika (Swimsuit)",
    fullName: "Kuromi Serika",
    lore: false,
    school: "Abydos",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 6,
    order: 183,
    height: 153,
    birthday: [6, 25],
    year: "1st Year",
    club: "Foreclosure Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10096,
    name: "Kanna (Swimsuit)",
    fullName: "Ogata Kanna",
    lore: false,
    school: "Valkyrie",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 2,
    order: 184,
    height: 166,
    birthday: [9, 7],
    year: "3rd Year",
    club: "Public Peace Bureau",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 20037,
    name: "Fubuki (Swimsuit)",
    fullName: "Nemugaki Fubuki",
    lore: false,
    school: "Valkyrie",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 4,
    order: 185,
    height: 148,
    birthday: [10, 21],
    year: "1st Year",
    club: "Public Safety Bureau",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 26012,
    name: "Kirino (Swimsuit)",
    fullName: "Nakatsukasa Kirino",
    lore: false,
    school: "Valkyrie",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 5,
    order: 186,
    height: 161,
    birthday: [10, 22],
    year: "1st Year",
    club: "Public Safety Bureau",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10097,
    name: "Moe (Swimsuit)",
    fullName: "Kazekura Moe",
    lore: false,
    school: "SRT",
    role: "Dealer",
    damage: "Sonic",
    weapon: "HG",
    exCost: 6,
    order: 187,
    height: 163,
    birthday: [9, 13],
    year: "1st Year",
    club: "RABBIT Squad",
    gifts: ["Airbook Rare"],
  },
  {
    id: 10098,
    name: "Hoshino (Armed)",
    fullName: "Takanashi Hoshino",
    lore: false,
    school: "Abydos",
    role: "Tank",
    damage: "Mystic",
    weapon: "SG",
    exCost: 4,
    order: 188,
    height: 145,
    birthday: [1, 2],
    year: "3rd Year",
    club: "Foreclosure Task Force",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10100,
    name: "Shiroko*Terror",
    fullName: "Sunaookami Shiroko",
    lore: true,
    school: "Abydos",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 3,
    order: 190,
    height: 165,
    birthday: [5, 16],
    year: "3rd Year",
    club: "Abydos Student Council",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 26013,
    name: "Atsuko (Swimsuit)",
    fullName: "Hakari Atsuko",
    lore: false,
    school: "Arius",
    role: "Healer",
    damage: "Sonic",
    weapon: "SMG",
    exCost: 2,
    order: 191,
    height: 158,
    birthday: [1, 20],
    year: "1st Year",
    club: "Arius Squad",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10101,
    name: "Saori (Swimsuit)",
    fullName: "Joumae Saori",
    lore: false,
    school: "Arius",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 7,
    order: 192,
    height: 167,
    birthday: [9, 3],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10102,
    name: "Hiyori (Swimsuit)",
    fullName: "Tsuchinaga Hiyori",
    lore: false,
    school: "Arius",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 4,
    order: 193,
    height: 155,
    birthday: [1, 8],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10103,
    name: "Marina (Qipao)",
    fullName: "Ikekura Marina",
    lore: false,
    school: "Red Winter",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 6,
    order: 194,
    height: 166,
    birthday: [11, 4],
    year: "2nd Year",
    club: "Red Winter Office",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20038,
    name: "Tomoe (Qipao)",
    fullName: "Sashiro Tomoe",
    lore: false,
    school: "Red Winter",
    role: "Support",
    damage: "Mystic",
    weapon: "SR",
    exCost: 3,
    order: 195,
    height: 165,
    birthday: [11, 10],
    year: "3rd Year",
    club: "Red Winter Office",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10104,
    name: "Reijo",
    fullName: "Kayama Reijo",
    lore: true,
    school: "Shanhaijing",
    role: "Support",
    damage: "Mystic",
    weapon: "AR",
    exCost: 3,
    order: 196,
    height: 169,
    birthday: [3, 3],
    year: "3rd Year",
    club: "Black Tortoise Promenade",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 20039,
    name: "Kisaki",
    fullName: "Ryuuge Kisaki",
    lore: true,
    school: "Shanhaijing",
    role: "Support",
    damage: "Sonic",
    weapon: "SMG",
    exCost: 3,
    order: 197,
    height: 142,
    birthday: [2, 19],
    year: "3rd Year",
    club: "Genryumon",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 10105,
    name: "Mari (Pop Idol)",
    fullName: "Iochi Mari",
    lore: false,
    school: "Trinity",
    role: "Healer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 2,
    order: 198,
    height: 151,
    birthday: [9, 12],
    year: "1st Year",
    club: "The Sisterhood",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10106,
    name: "Sakurako (Pop Idol)",
    fullName: "Utazumi Sakurako",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 3,
    order: 199,
    height: 160,
    birthday: [10, 4],
    year: "3rd Year",
    club: "The Sisterhood",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 16016,
    name: "Mine (Pop Idol)",
    fullName: "Aomori Mine",
    lore: false,
    school: "Trinity",
    role: "Tank",
    damage: "Explosive",
    weapon: "SG",
    exCost: 3,
    order: 200,
    height: 168,
    birthday: [11, 23],
    year: "3rd Year",
    club: "Remedial Knights",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10107,
    name: "Chiaki",
    fullName: "Motomiya Chiaki",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 6,
    order: 201,
    height: 167,
    birthday: [9, 22],
    year: "2nd Year",
    club: "Pandemonium Society",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20040,
    name: "Satsuki",
    fullName: "Kyougoku Satsuki",
    lore: true,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 202,
    height: 172,
    birthday: [4, 10],
    year: "3rd Year",
    club: "Pandemonium Society",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10108,
    name: "Yuuka (Pajamas)",
    fullName: "Hayase Yuuka",
    lore: false,
    school: "Millennium",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 2,
    order: 203,
    height: 156,
    birthday: [3, 14],
    year: "2nd Year",
    club: "Seminar",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10109,
    name: "Noa (Pajamas)",
    fullName: "Ushio Noa",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "HG",
    exCost: 5,
    order: 204,
    height: 161,
    birthday: [4, 13],
    year: "2nd Year",
    club: "Seminar",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10110,
    name: "Seia",
    fullName: "Yurizono Seia",
    lore: true,
    school: "Trinity",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 205,
    height: 149,
    birthday: [9, 29],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10112,
    name: "Asuna (School)",
    fullName: "Ichinose Asuna",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Explosive",
    weapon: "AR",
    exCost: 3,
    order: 206,
    height: 167,
    birthday: [3, 24],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 26014,
    name: "Karin (School)",
    fullName: "Kakudate Karin",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 7,
    order: 207,
    height: 170,
    birthday: [2, 2],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10111,
    name: "Neru (School)",
    fullName: "Mikamo Neru",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 1,
    order: 208,
    height: 146,
    birthday: [8, 17],
    year: "3rd Year",
    club: "Cleaning & Clearing",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20041,
    name: "Rio",
    fullName: "Tsukatsuki Rio",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "HG",
    exCost: 2,
    order: 209,
    height: 171,
    birthday: [6, 6],
    year: "3rd Year",
    club: "Seminar",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20042,
    name: "Maki (Camp)",
    fullName: "Konuri Maki",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 4,
    order: 210,
    height: 149,
    birthday: [8, 1],
    year: "1st Year",
    club: "Veritas",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10113,
    name: "Sena (Casual)",
    fullName: "Himuro Sena",
    lore: false,
    school: "Gehenna",
    role: "Healer",
    damage: "Sonic",
    weapon: "GL",
    exCost: 5,
    order: 211,
    height: 155,
    birthday: [4, 7],
    year: "3rd Year",
    club: "Medical Emergency Club",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10114,
    name: "Juri (Part-Timer)",
    fullName: "Ushimaki Juri",
    lore: false,
    school: "Gehenna",
    role: "Tank",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 212,
    height: 170,
    birthday: [10, 20],
    year: "1st Year",
    club: "School Lunch Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 20043,
    name: "Izumi (New Year)",
    fullName: "Shishidou Izumi",
    lore: false,
    school: "Gehenna",
    role: "Support",
    damage: "Explosive",
    weapon: "MG",
    exCost: 5,
    order: 213,
    height: 161,
    birthday: [5, 11],
    year: "2nd Year",
    club: "Gourmet Research Society",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10115,
    name: "Rei",
    fullName: "Nomasa Rei",
    lore: true,
    school: "Millennium",
    role: "Dealer",
    damage: "Sonic",
    weapon: "RL",
    exCost: 4,
    order: 214,
    height: 159,
    birthday: [8, 9],
    year: "1st Year",
    club: "Athletics Training Club",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20044,
    name: "Sumire (Part-Timer)",
    fullName: "Otohana Sumire",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "SG",
    exCost: 3,
    order: 215,
    height: 167,
    birthday: [8, 20],
    year: "2nd Year",
    club: "Athletics Training Club",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 10116,
    name: "Saori (Dress)",
    fullName: "Joumae Saori",
    lore: false,
    school: "Arius",
    role: "Dealer",
    damage: "Sonic",
    weapon: "AR",
    exCost: 4,
    order: 216,
    height: 167,
    birthday: [9, 3],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10117,
    name: "Hikari",
    fullName: "Tachibana Hikari",
    lore: true,
    school: "Highlander",
    role: "Support",
    damage: "Sonic",
    weapon: "HG",
    exCost: 2,
    order: 217,
    height: 147,
    birthday: [6, 14],
    year: "1st Year",
    club: "CCC",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10118,
    name: "Nozomi",
    fullName: "Tachibana Nozomi",
    lore: true,
    school: "Highlander",
    role: "Dealer",
    damage: "Sonic",
    weapon: "HG",
    exCost: 4,
    order: 218,
    height: 147,
    birthday: [6, 14],
    year: "1st Year",
    club: "CCC",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 16017,
    name: "Aoba",
    fullName: "Utsumi Aoba",
    lore: true,
    school: "Highlander",
    role: "Tank",
    damage: "Sonic",
    weapon: "SG",
    exCost: 3,
    order: 219,
    height: 151,
    birthday: [7, 19],
    year: "2nd Year",
    club: "Freight Logistics Department",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20045,
    name: "Pina (Guide)",
    fullName: "Asahina Pina",
    lore: false,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Explosive",
    weapon: "MG",
    exCost: 6,
    order: 220,
    height: 165,
    birthday: [11, 3],
    year: "1st Year",
    club: "Festival Operations Department",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10119,
    name: "Nagusa",
    fullName: "Goryou Nagusa",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 4,
    order: 221,
    height: 161,
    birthday: [12, 7],
    year: "3rd Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 20046,
    name: "Niya",
    fullName: "Amachi Niya",
    lore: true,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Sonic",
    weapon: "HG",
    exCost: 4,
    order: 222,
    height: 166,
    birthday: [1, 1],
    year: "3rd Year",
    club: "Yin-Yang Club",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 10120,
    name: "Natsu (Band)",
    fullName: "Yutori Natsu",
    lore: false,
    school: "Trinity",
    role: "Healer",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 4,
    order: 223,
    height: 152,
    birthday: [12, 4],
    year: "1st Year",
    club: "After-School Sweets Club",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 10121,
    name: "Yukari (Swimsuit)",
    fullName: "Kadenokouji Yukari",
    lore: false,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 6,
    order: 224,
    height: 155,
    birthday: [6, 16],
    year: "1st Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 13014,
    name: "Renge (Swimsuit)",
    fullName: "Fuwa Renge",
    lore: false,
    school: "Hyakkiyako",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 3,
    order: 225,
    height: 157,
    birthday: [7, 23],
    year: "2nd Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20047,
    name: "Kikyou (Swimsuit)",
    fullName: "Kiryuu Kikyou",
    lore: false,
    school: "Hyakkiyako",
    role: "Support",
    damage: "Sonic",
    weapon: "SR",
    exCost: 4,
    order: 226,
    height: 160,
    birthday: [8, 8],
    year: "2nd Year",
    club: "Hyakkaryouran Resolution Council",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10123,
    name: "Seia (Swimsuit)",
    fullName: "Yurizono Seia",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 227,
    height: 149,
    birthday: [9, 29],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10124,
    name: "Hasumi (Swimsuit)",
    fullName: "Hanekawa Hasumi",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Piercing",
    weapon: "SR",
    exCost: 5,
    order: 228,
    height: 179,
    birthday: [12, 12],
    year: "3rd Year",
    club: "Justice Task Force",
    gifts: ["Mille-Feuille Traditional Parfait"],
  },
  {
    id: 26015,
    name: "Ichika (Swimsuit)",
    fullName: "Nakamasa Ichika",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Sonic",
    weapon: "AR",
    exCost: 2,
    order: 229,
    height: 163,
    birthday: [11, 11],
    year: "2nd Year",
    club: "Justice Task Force",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 20048,
    name: "Nagisa (Swimsuit)",
    fullName: "Kirifuji Nagisa",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Sonic",
    weapon: "HG",
    exCost: 3,
    order: 230,
    height: 160,
    birthday: [7, 4],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ["Lace Pillow"],
  },
  {
    id: 10122,
    name: "Mika (Swimsuit)",
    fullName: "Misono Mika",
    lore: false,
    school: "Trinity",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SMG",
    exCost: 4,
    order: 231,
    height: 157,
    birthday: [5, 8],
    year: "3rd Year",
    club: "Tea Party",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10125,
    name: "Eri",
    fullName: "Shirao Eri",
    lore: true,
    school: "Wildhunt",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SR",
    exCost: 5,
    order: 232,
    height: 158,
    birthday: [10, 31],
    year: "2nd Year",
    club: "Occult Society (Dormitory 4, Unit 404)",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10126,
    name: "Kanoe",
    fullName: "Itagaki Kanoe",
    lore: true,
    school: "Wildhunt",
    role: "Tank",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 233,
    height: 144,
    birthday: [11, 2],
    year: "3rd Year",
    club: "Occult Society (Dormitory 4, Unit 404)",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 20049,
    name: "Misaki (Swimsuit)",
    fullName: "Imashino Misaki",
    lore: false,
    school: "Arius",
    role: "Dealer",
    damage: "Explosive",
    weapon: "RL",
    exCost: 6,
    order: 234,
    height: 163,
    birthday: [1, 13],
    year: "2nd Year",
    club: "Arius Squad",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10127,
    name: "Miyo",
    fullName: "Sakurai Miyo",
    lore: true,
    school: "Wildhunt",
    role: "Support",
    damage: "Sonic",
    weapon: "SR",
    exCost: 2,
    order: 235,
    height: 155,
    birthday: [8, 24],
    year: "2nd Year",
    club: "Free Trade Cartel (Dormitory 5, Unit 402)",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10128,
    name: "Fuyu",
    fullName: "Wakasa Fuyu",
    lore: true,
    school: "Wildhunt",
    role: "Support",
    damage: "Sonic",
    weapon: "HG",
    exCost: 2,
    order: 236,
    height: 173,
    birthday: [9, 5],
    year: "2nd Year",
    club: "Free Trade Cartel (Dormitory 5, Unit 402)",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 20050,
    name: "Ritsu",
    fullName: "Usuba Ritsu",
    lore: true,
    school: "Wildhunt",
    role: "Support",
    damage: "Mystic",
    weapon: "SMG",
    exCost: 3,
    order: 237,
    height: 140,
    birthday: [3, 6],
    year: "1st Year",
    club: "Free Trade Cartel (Dormitory 5, Unit 402)",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 20051,
    name: "Reisa (Magical)",
    fullName: "Uzawa Reisa",
    lore: false,
    school: "Trinity",
    role: "Healer",
    damage: "Sonic",
    weapon: "SG",
    exCost: 4,
    order: 238,
    height: 153,
    birthday: [5, 31],
    year: "1st Year",
    club: "Trinity's Vigilante Crew",
    gifts: ["Streets of Thugs Vol. 1"],
  },
  {
    id: 10129,
    name: "Suzumi (Magical)",
    fullName: "Morizuki Suzumi",
    lore: false,
    school: "Trinity",
    role: "Support",
    damage: "Sonic",
    weapon: "AR",
    exCost: 5,
    order: 239,
    height: 162,
    birthday: [8, 31],
    year: "2nd Year",
    club: "Trinity's Vigilante Crew",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 16018,
    name: "Rabu",
    fullName: "Komakaze Rabu",
    lore: true,
    school: "Trinity",
    role: "Dealer",
    damage: "Sonic",
    weapon: "SG",
    exCost: 4,
    order: 240,
    height: 161,
    birthday: [5, 6],
    year: "Drop out",
    club: "None",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10130,
    name: "Subaru",
    fullName: "Kakehashi Subaru",
    lore: true,
    school: "Arius",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 4,
    order: 241,
    height: 166,
    birthday: [3, 9],
    year: "3rd Year",
    club: "Nicomedia's Troop",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 10131,
    name: "Takane",
    fullName: "Miyoshi Takane",
    lore: true,
    school: "Red Winter",
    role: "Healer",
    damage: "Mystic",
    weapon: "HG",
    exCost: 2,
    order: 242,
    height: 148,
    birthday: [6, 18],
    year: "2nd Year",
    club: "Publishing Department",
    gifts: ["Music Concert Ticket"],
  },
  {
    id: 20052,
    name: "Yakumo",
    fullName: "Aramaki Yakumo",
    lore: true,
    school: "Red Winter",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 4,
    order: 243,
    height: 144,
    birthday: [5, 18],
    year: "3rd Year",
    club: "Publishing Department",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10132,
    name: "Tsukuyo (Dress)",
    fullName: "Ono Tsukuyo",
    lore: false,
    school: "Hyakkiyako",
    role: "Tank",
    damage: "Piercing",
    weapon: "SMG",
    exCost: 4,
    order: 244,
    height: 180,
    birthday: [4, 5],
    year: "1st Year",
    club: "Ninjutsu Research Club",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 20053,
    name: "Michiru (Dress)",
    fullName: "Chidori Michiru",
    lore: false,
    school: "Hyakkiyako",
    role: "Healer",
    damage: "Explosive",
    weapon: "SG",
    exCost: 2,
    order: 245,
    height: 153,
    birthday: [2, 22],
    year: "3rd Year",
    club: "Ninjutsu Research Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10133,
    name: "Rio (Armed)",
    fullName: "Tsukatsuki Rio",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 4,
    order: 246,
    height: 171,
    birthday: [6, 6],
    year: "3rd Year",
    club: "Seminar",
    gifts: ["Airbook Rare"],
  },
  {
    id: 16019,
    name: "Toki (Armed)",
    fullName: "Asuma Toki",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 247,
    height: 165,
    birthday: [8, 16],
    year: "1st Year",
    club: "Cleaning & Clearing",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 20054,
    name: "Himari (Armed)",
    fullName: "Akeboshi Himari",
    lore: false,
    school: "Millennium",
    role: "T.S.",
    damage: "Piercing",
    weapon: "HG",
    exCost: 3,
    order: 248,
    height: 162,
    birthday: [12, 10],
    year: "3rd Year",
    club: "Super Phenomenon Task Force",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 10134,
    name: "Aris (Armed)",
    fullName: "Tendou Aris",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Mystic",
    weapon: "AR",
    exCost: 4,
    order: 249,
    height: 152,
    birthday: [3, 25],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10135,
    name: "Kei",
    fullName: "Kei",
    lore: true,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "RG",
    exCost: 2,
    order: 250,
    height: 152,
    birthday: [3, 25],
    year: "1st Year",
    club: "Super Phenomenon Task Force",
    gifts: ['Samuela "The Beyond"'],
  },
  {
    id: 10136,
    name: "Eimi (Armed)",
    fullName: "Izumimoto Eimi",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 5,
    order: 251,
    height: 167,
    birthday: [5, 1],
    year: "1st Year",
    club: "Super Phenomenon Task Force",
    gifts: ["Nutrient-Packed Multivitamin Gummies"],
  },
  {
    id: 20055,
    name: "Yuzu (Armed)",
    fullName: "Hanaoka Yuzu",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "GL",
    exCost: 4,
    order: 252,
    height: 150,
    birthday: [8, 12],
    year: "1st Year",
    club: "Game Development Department",
    gifts: ["Airbook Rare"],
  },
  {
    id: 20056,
    name: "Koyuki (Pajamas)",
    fullName: "Kurosaki Koyuki",
    lore: false,
    school: "Millennium",
    role: "Support",
    damage: "Mystic",
    weapon: "MG",
    exCost: 3,
    order: 253,
    height: 149,
    birthday: [2, 14],
    year: "1st Year",
    club: "Seminar",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 10137,
    name: "Konoka",
    fullName: "Shima Konoka",
    lore: true,
    school: "Valkyrie",
    role: "Tank",
    damage: "Mystic",
    weapon: "SG",
    exCost: 3,
    order: 254,
    height: 165,
    birthday: [8, 19],
    year: "2nd Year",
    club: "Public Peace Bureau",
    gifts: ["Three Times a Day Dumbbell Set"],
  },
  {
    id: 10138,
    name: "Rena",
    fullName: "Kinui Rena",
    lore: true,
    school: "Wildhunt",
    role: "Support",
    damage: "Explosive",
    weapon: "HG",
    exCost: 3,
    order: 255,
    height: 152,
    birthday: [9, 21],
    year: "1st Year",
    club: "Occult Society (Dormitory 4, Unit 404)",
    gifts: ["Sewing Kit"],
  },
  {
    id: 20057,
    name: "Akane (School)",
    fullName: "Murokasa Akane",
    lore: false,
    school: "Millennium",
    role: "Dealer",
    damage: "Explosive",
    weapon: "HG",
    exCost: 4,
    order: 256,
    height: 164,
    birthday: [4, 1],
    year: "2nd Year",
    club: "Cleaning & Clearing",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10139,
    name: "Niko",
    fullName: "Yoshino Niko",
    lore: true,
    school: "SRT",
    role: "Support",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 257,
    height: 160,
    birthday: [2, 11],
    year: "3rd Year",
    club: "FOX Squad",
    gifts: ["Sewing Kit"],
  },
  {
    id: 10140,
    name: "Kurumi",
    fullName: "Takakura Kurumi",
    lore: true,
    school: "SRT",
    role: "Tank",
    damage: "Explosive",
    weapon: "SMG",
    exCost: 3,
    order: 258,
    height: 151,
    birthday: [9, 30],
    year: "3rd Year",
    club: "FOX Squad",
    gifts: ['Board Game "The Life"'],
  },
  {
    id: 16020,
    name: "Otogi",
    fullName: "Tenjinyama Otogi",
    lore: true,
    school: "SRT",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SR",
    exCost: 4,
    order: 259,
    height: 150,
    birthday: [5, 20],
    year: "3rd Year",
    club: "FOX Squad",
    gifts: ["Antique Egg Handicraft"],
  },
  {
    id: 20058,
    name: "Erika",
    fullName: "Hatami Erika",
    lore: true,
    school: "Gehenna",
    role: "Support",
    damage: "Sonic",
    weapon: "SG",
    exCost: 3,
    order: 260,
    height: 166,
    birthday: [2, 1],
    year: "2nd Year",
    club: "Twinkle Twinkle Club",
    gifts: ["Sophisticated Hairbrush"],
  },
  {
    id: 10141,
    name: "Haruka (Dress)",
    fullName: "Igusa Haruka",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Explosive",
    weapon: "SG",
    exCost: 4,
    order: 261,
    height: 157,
    birthday: [5, 13],
    year: "1st Year",
    club: "Problem Solver 68",
    gifts: ["Finest Maple Bonsai"],
  },
  {
    id: 20059,
    name: "Mutsuki (Dress)",
    fullName: "Asagi Mutsuki",
    lore: false,
    school: "Gehenna",
    role: "Dealer",
    damage: "Mystic",
    weapon: "MG",
    exCost: 6,
    order: 262,
    height: 144,
    birthday: [7, 29],
    year: "2nd Year",
    club: "Problem Solver 68",
    gifts: ['Board Game "The Life"'],
  },
];
